### ISSUE TITLE
Precompile assets: Exception in thread "main" java.io.FileNotFoundException

### ISSUE THREAD

**Issue by ivankravets** [circleci/frontend#46]
I've done all steps described in README. However, can't regenerate assets. See log

```
➜  circle-frontend git:(master) lein run -m frontend.tasks.http/precompile-assets
Updating {:path "js/hosted/intercom2.js", :url "https://widget.intercom.io/widget/vnk4oztr"}
Updating {:path "js/hosted/pusher.min.js", :url "https://js.pusher.com/2.2/pusher.min.js"}
Stefon options: {:asset-roots ["resources/assets"], :precompiles ("js/om-dev.js.stefon" "js/om-production.js.stefon" "css/app.css" "img/docs/heroku-step1.png" "img/docs/heroku-step2.png" "img/logo.png" "img/outer/docs/artifacts_listing.png" "img/outer/docs/coverage_example.png" "img/outer/docs/ssh-build-button-current.png" "img/outer/docs/ssh-build-button-rebuild.png" "img/outer/docs/ssh-build-details.png" "img/outer/about/paul.png" "img/outer/about/allen.png" "img/outer/about/david.png" "img/outer/about/jenneviere.png" "img/outer/about/daniel.png" "img/outer/about/mahmood.png" "img/outer/about/gordon.png" "img/outer/about/danny.png" "img/outer/languages/build-screenshot-python.png" "img/docs/artifacts.png" "img/status-logos/success.svg" "img/status-logos/failure.svg" "img/status-logos/logo.svg" "img/outer/stories/john.jpg" "img/outer/stories/arthur.jpg" "docs/adding-read-write-deployment-key.md" "docs/android.md" "docs/api.md" "docs/background-process.md" "docs/browser-debugging.md" "docs/browser-testing-with-sauce-labs.md" "docs/build-artifacts.md" "docs/bundler-latest.md" "docs/cabal-test-timeout.md" "docs/cant-follow.md" "docs/capybara-timeout.md" "docs/chromedriver-moving-elements.md" "docs/clojure-12.md" "docs/code-coverage.md" "docs/composer-api-rate-limit.md" "docs/config-sample.md" "docs/configuration.md" "docs/continuous-deployment-with-ninefold.md" "docs/continuous-deployment-with-heroku.md" "docs/continuous-deployment.md" "docs/deploy-google-app-engine.md" "docs/deploy-bluemix.md" "docs/docker.md" "docs/dont-run.md" "docs/ec2ip-and-security-group.md" "docs/environment-variables.md" "docs/environment.md" "docs/external-resources.md" "docs/faq.md" "docs/file-ordering.md" "docs/filesystem.md" "docs/fork-pr-builds.md" "docs/getting-started.md" "docs/gettingstarted.md" "docs/git-bundle-install.md" "docs/git-npm-install.md" "docs/git-pip-install.md" "docs/github-3rdparty-app-restrictions.md" "docs/github-permissions.md" "docs/github-privacy.md" "docs/github-security-ssh-keys.md" "docs/how-cache-works.md" "docs/how-parallelism-works.md" "docs/how-to.md" "docs/installing-custom-software.md" "docs/installing-elasticsearch.md" "docs/introduction-to-continuous-deployment.md" "docs/ios.md" "docs/language-haskell.md" "docs/language-java.md" "docs/language-nodejs.md" "docs/language-php.md" "docs/language-python.md" "docs/language-ruby-on-rails.md" "docs/language-scala.md" "docs/languages.md" "docs/look-at-code.md" "docs/manually.md" "docs/missing-dir.md" "docs/missing-file.md" "docs/mobile.md" "docs/nightly-builds.md" "docs/not-specified-ruby-commands.md" "docs/unrecognized-ruby-version.md" "docs/oom.md" "docs/parallel-manual-setup.md" "docs/parallelism.md" "docs/parameterized-builds.md" "docs/permissions-and-access-during-deployment.md" "docs/php-memcached-compile-error.md" "docs/polling-project-status.md" "docs/privacy-security.md" "docs/pushing-packages-to-packagecloud.md" "docs/reference.md" "docs/requires-admin.md" "docs/rspec-exit-codes.md" "docs/ruby-debugger-problems.md" "docs/ruby-exception-during-schema-load.md" "docs/shipio-to-circleci-migration.md" "docs/skip-a-build.md" "docs/ssh-build.md" "docs/ssh-between-build-containers.md" "docs/status-badges.md" "docs/test-metadata.md" "docs/test-with-solr.md" "docs/test-with-sphinx.md" "docs/time-day.md" "docs/time-date.md" "docs/time-seconds.md" "docs/troubleshooting-browsers.md" "docs/troubleshooting-clojure.md" "docs/troubleshooting-guide.md" "docs/troubleshooting-haskell.md" "docs/troubleshooting-nodejs.md" "docs/troubleshooting-php.md" "docs/troubleshooting-python.md" "docs/troubleshooting-ruby.md" "docs/troubleshooting.md" "docs/unusual.md" "docs/what-happens.md" "docs/unexpected-rake-errors.md" "docs/manifest.json" "js/hosted/intercom2.js" "js/hosted/pusher.min.js"), :serving-root "resources/public", :manifest-file "resources/public/assets/stefon-manifest.json", :mode :production}
compile-stefon-with-sourcemaps:  js/common.js.stefon
compile-stefon-with-sourcemaps:  vendor/console-shim.js
compile-stefon-with-sourcemaps:  ../components/jquery/index.js
compile-stefon-with-sourcemaps:  ../components/bootstrap3-typeahead/bootstrap3-typeahead.min.js
compile-stefon-with-sourcemaps:  ../components/jquery-placeholder/jquery.placeholder.min.js
compile-stefon-with-sourcemaps:  ../components/uri.js/src/URI.min.js
compile-stefon-with-sourcemaps:  ../components/viewport-units-buggyfill/viewport-units-buggyfill.js
compile-stefon-with-sourcemaps:  ../components/marked/lib/marked.js
compile-stefon-with-sourcemaps:  ../components/d3/d3.min.js
compile-stefon-with-sourcemaps:  js/bootstrap.js.stefon
compile-stefon-with-sourcemaps:  ../components/bootstrap/js/affix.js
compile-stefon-with-sourcemaps:  ../components/bootstrap/js/alert.js
compile-stefon-with-sourcemaps:  ../components/bootstrap/js/button.js
compile-stefon-with-sourcemaps:  ../components/bootstrap/js/dropdown.js
compile-stefon-with-sourcemaps:  ../components/bootstrap/js/modal.js
compile-stefon-with-sourcemaps:  ../components/bootstrap/js/scrollspy.js
compile-stefon-with-sourcemaps:  ../components/bootstrap/js/tooltip.js
compile-stefon-with-sourcemaps:  ../components/bootstrap/js/popover.js
compile-stefon-with-sourcemaps:  ../components/bootstrap/js/transition.js
compile-stefon-with-sourcemaps:  js/module_setup.coffee
compile-stefon-with-sourcemaps:  js/libs/asset-path.coffee
compile-stefon-with-sourcemaps:  js/libs/existing-user-heuristics.coffee
compile-stefon-with-sourcemaps:  js/libs/terminal.coffee
compile-stefon-with-sourcemaps:  js/libs/phantomjs-hack.js
compile-stefon-with-sourcemaps:  js/inner/config_diagnostic.coffee
compile-stefon-with-sourcemaps:  js/outer/versions.coffee
compile-stefon-with-sourcemaps:  js/outer/api_data.coffee
compile-stefon-with-sourcemaps:  js/stefon-hack-for-om.coffee.ref
compile-stefon-with-sourcemaps:  js/common.js.stefon
compile-stefon-with-sourcemaps:  vendor/console-shim.js
compile-stefon-with-sourcemaps:  ../components/jquery/index.js
compile-stefon-with-sourcemaps:  ../components/bootstrap3-typeahead/bootstrap3-typeahead.min.js
compile-stefon-with-sourcemaps:  ../components/jquery-placeholder/jquery.placeholder.min.js
compile-stefon-with-sourcemaps:  ../components/uri.js/src/URI.min.js
compile-stefon-with-sourcemaps:  ../components/viewport-units-buggyfill/viewport-units-buggyfill.js
compile-stefon-with-sourcemaps:  ../components/marked/lib/marked.js
compile-stefon-with-sourcemaps:  ../components/d3/d3.min.js
compile-stefon-with-sourcemaps:  js/bootstrap.js.stefon
compile-stefon-with-sourcemaps:  ../components/bootstrap/js/affix.js
compile-stefon-with-sourcemaps:  ../components/bootstrap/js/alert.js
compile-stefon-with-sourcemaps:  ../components/bootstrap/js/button.js
compile-stefon-with-sourcemaps:  ../components/bootstrap/js/dropdown.js
compile-stefon-with-sourcemaps:  ../components/bootstrap/js/modal.js
compile-stefon-with-sourcemaps:  ../components/bootstrap/js/scrollspy.js
compile-stefon-with-sourcemaps:  ../components/bootstrap/js/tooltip.js
compile-stefon-with-sourcemaps:  ../components/bootstrap/js/popover.js
compile-stefon-with-sourcemaps:  ../components/bootstrap/js/transition.js
compile-stefon-with-sourcemaps:  js/module_setup.coffee
compile-stefon-with-sourcemaps:  js/libs/asset-path.coffee
compile-stefon-with-sourcemaps:  js/libs/existing-user-heuristics.coffee
compile-stefon-with-sourcemaps:  js/libs/terminal.coffee
compile-stefon-with-sourcemaps:  js/libs/phantomjs-hack.js
compile-stefon-with-sourcemaps:  js/inner/config_diagnostic.coffee
compile-stefon-with-sourcemaps:  js/outer/versions.coffee
compile-stefon-with-sourcemaps:  js/outer/api_data.coffee
compile-stefon-with-sourcemaps:  js/stefon-hack-for-om.coffee.ref
compile-stefon-with-sourcemaps:  ../public/cljs/production/frontend.js
Exception in thread "main" java.io.FileNotFoundException: Couldn't find ../public/cljs/production/frontend.js in resources/assets, compiling:(/private/var/folders/nj/nt38kxwd2xxfl5l42np_w7qw0000gn/T/form-init343043099577919138.clj:1:124)
	at clojure.lang.Compiler.load(Compiler.java:7239)
	at clojure.lang.Compiler.loadFile(Compiler.java:7165)
	at clojure.main$load_script.invoke(main.clj:275)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invoke(main.clj:308)
	at clojure.main$null_opt.invoke(main.clj:343)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.io.FileNotFoundException: Couldn't find ../public/cljs/production/frontend.js in resources/assets
	at stefon.asset$file_not_found.invoke(asset.clj:29)
	at stefon.asset$read_file.invoke(asset.clj:40)
	at stefon.asset$compile.invoke(asset.clj:96)
	at frontend.stefon_with_sourcemaps$compile_stefon_with_sourcemaps.invoke(stefon_with_sourcemaps.clj:21)
	at stefon.asset$apply_pipeline.invoke(asset.clj:88)
	at stefon.asset$compile.invoke(asset.clj:97)
	at stefon.asset$compile_and_save.invoke(asset.clj:105)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:630)
	at stefon.asset$find_and_compile_and_save.invoke(asset.clj:114)
	at stefon.precompile$precompile$iter__2409__2413$fn__2414$fn__2415.invoke(precompile.clj:37)
	at stefon.precompile$precompile$iter__2409__2413$fn__2414.invoke(precompile.clj:36)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:507)
	at clojure.core$seq__4128.invoke(core.clj:137)
	at clojure.core$dorun.invoke(core.clj:3009)
	at clojure.core$doall.invoke(core.clj:3025)
	at stefon.precompile$precompile.invoke(precompile.clj:35)
	at stefon.core$precompile.invoke(core.clj:61)
	at frontend.tasks.http$precompile_assets.invoke(http.clj:43)
	at clojure.lang.Var.invoke(Var.java:375)
	at user$eval5.invoke(form-init343043099577919138.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.eval(Compiler.java:6772)
	at clojure.lang.Compiler.load(Compiler.java:7227)
	... 11 more
```

**Comment by JustinC474** [comment]
Hi Ivan! It looks like you need to generate your `frontend.js` file. You can do this by running the command `lein cljsbuild once`. Here are the instructions in the README: https://github.com/circleci/frontend#asset-compilation-errors.

Hope that helps!

**Comment by ivankravets** [comment]
Thanks @JustinC474! It helped me!

P.S: I'm working on "CI for Embedded Platforms" docs for Circle CI (like, https://github.com/travis-ci/docs-travis-ci-com/pull/387/files). How I can place the new "CI for Embedded Platforms" item in the left sidebar? Which files are responded for it?

**Comment by JustinC474** [comment]
@ivankravets - here is the where the html for the left nav lives: https://github.com/circleci/frontend/blob/master/src-cljs/frontend/components/aside.cljs#L361

You should be able to use the other items as examples for adding a "CI for Embedded Platforms" link - good luck and feel free to @mention me if you run into any other issues!

**Comment by ivankravets** [comment]
Let's place the link here https://circleci.com/docs/how-to (at the bottom of the list)

The file name will be `/docs/ci-embedded-platforms.md` and title `CI for Embedded Platforms`

**Comment by ivankravets** [comment]
@JustinC474  Could you help me to place the link here https://circleci.com/docs/how-to (at the bottom of the list)

The file name will be `/docs/ci-embedded-platforms.md` and title `CI for Embedded Platforms`
